### ISSUE TITLE
Swipe Inception

### ISSUE THREAD

**Issue by zetura** [oliviertassinari/react-swipeable-views#131]
Hello,

I'm actually facing a small issue. I am creating a project to be able to swipe between slides, but you can have swipeable views into the main swipeable view : https://github.com/zetura/slidr
What would be great, is that when you swipe on the left/right and there is no slide left, we swipe on the parent swipeable view. Do you think this would be possible to implement ?

Thanks

**Comment by oliviertassinari** [comment]
I think that the feature would require changing the [`preventDefault`](https://github.com/oliviertassinari/react-swipeable-views/blob/master/src/SwipeableViews.js#L294) logic.

**Comment by zetura** [comment]
I find a way to do it, but on the actual version available on npm.
I moved the index variables over the `preventDefault`, and changed the `preventDefault` for `stopPropagation`, and I return if the index is over the indexMax or under 0.
I had to change for `stopPropagation` because the `preventDefault` stops completely the touch move event on the parent at the start.

```
var indexMax = _react.Children.count(_this.props.children) - 1;

      var index = _this.state.indexLatest + (_this.startX - touch.pageX) / _this.startWidth;

      if((index < 0 || index > indexMax)) {
        return;
      }

      // Prevent native scrolling
      event.stopPropagation();
```

**Comment by oliviertassinari** [comment]
This issue is also linked to https://github.com/oliviertassinari/react-swipeable-views/issues/26#issuecomment-241551403. They both deals with nested scroll container.
The overall UX should be pretty close.

@zetura Do you mind submitting a PR so I can have a better view of your approach?
That sounds something that needs to be configurable. I'm wondering if a property would be useful here.

**Comment by zetura** [comment]
@oliviertassinari I can do that, yes, but since your code changed a lot since the last npm version. I'm not sure it would work the same way.

**Comment by pbellon** [comment]
Hi there, I'm having the same issue but I don't see where I could customize `SwipeableViews` to have this behavior. Let me show with a schema (A and B are `SwipeableViews`): 
![image](https://cloud.githubusercontent.com/assets/1018824/20342278/1bd19946-abea-11e6-8e1c-db99b81d1053.png)
The issue is to be able to swipe in A when we arrive at the last slide of B. However the only way to do that is to swipe outside B.
