### ISSUE TITLE
Disable touch events in one direction

### ISSUE THREAD

**Issue by jarandmi** [oliviertassinari/react-swipeable-views#191]
Is it possible to disable touch event when trying to slide to the right, but not to the left?

**Comment by oliviertassinari** [comment]
Would that [comment](https://github.com/oliviertassinari/react-swipeable-views/issues/179#issuecomment-257441139) help?

**Comment by jarandmi** [comment]
Yeah, maybe. But i cant get it to work like i want it to.

`goToSlide = (index) => {
        let oldTabIndex = this.props.registerTab;
        if(index < oldTabIndex){
            this.props.changeRegisterTab(index)
        }
        else {
            this.props.changeRegisterTab(oldTabIndex)
        }
    }`

changeRegisterTab updates the redux store, and the store gets the right tabIndex, but it still slides to the next and prev slide.

This is my component

`<SwipeableViews
                children={ FormInputs }
                slideStyle={ slideStyle }
                containerStyle={{ height: "100%" }}
                resistance={ true }
                className="list"
                index={ this.props.registerTab }
                onChangeIndex={ this.goToSlide }`

**Comment by jarandmi** [comment]
Ah, its because of the async callback from setState(). I got it to work with setTimeout

```javascript
goToSlide = (index) => {
        let oldTabIndex = this.props.registerTab;
        this.props.changeRegisterTab(index)

        setTimeout(() => {
            if(index < oldTabIndex){
                this.props.changeRegisterTab(oldTabIndex)
            }
        }, 1)
    }
`

**Comment by oliviertassinari** [comment]
@jarandmi Right, that point is quite tricky. The component isn't fully controllable.
It keeps an internal state for performances concern.
So you gonna need to render it twice in order to get a proper rejection of the navigation.
As far as I know, the dispatch action of redux is synchronously calling the render method.
So you shouldn't have any race condition here.
I'm closing the issue. Hopefully, that's gonna help others.
