### ISSUE TITLE
Flickering on slide in safari

### ISSUE THREAD

**Issue by kimown** [oliviertassinari/react-swipeable-views#192]
Only occurs in safari (desktop and mobile), when I change the slider, the whole page is flickering.(it occurs everytime when changing slider, but licecap can't capture every frame, so it only show the flickering when the index=13 and index=14 )
![untitled](https://cloud.githubusercontent.com/assets/7932380/20405248/2c9d5bd4-ad43-11e6-9abc-ccba32f6a534.gif)

Other browser, like chrome and firefox don't have this problem.

here is my code:
[react-swipeable.zip](https://github.com/oliviertassinari/react-swipeable-views/files/598330/react-swipeable.zip)

I spend a lot time searching and trying to solve this problem, it doesn't success. I doubt It is  a CSS3 transform bug in safari, but I am not sure what is the real reason. thanks.

**Comment by kimown** [comment]
@oliviertassinari  I am sorry for disturbing you again, but I don't know how to find the real reason of the problem, I have tried many solution I can found from Internet, like 
``` css
-webkit-backface-visibility: hidden;
```
they did works, but the flicker still exists, not frequently, but I want to remove the flicker completely like other browsers, can you give me some suggestions or advice, thanks in advance.

**Comment by oliviertassinari** [comment]
@kimown Interesting, I'm wondering what's going on. Could you provide a reproduction test case on http://www.webpackbin.com/? That would help a lot, thanks!

**Comment by oliviertassinari** [comment]
Thanks for the archive, that was quite useful. The root issue seems to be at *react-motion* level. I have opened an issue: https://github.com/chenglou/react-motion/issues/404.

**Comment by yoadsn** [comment]
I'm considering the usage of `react-swipeable-views` for a new component - Should this be a concern? Does it reproduce on every use case of this library when rendered on safari? (Assuming safari support is important and mandatory for me)
Is there any simple workaround?

**Comment by yoadsn** [comment]
@oliviertassinari See my comments on the https://github.com/chenglou/react-motion/issues/404 issue you opened. This might provide an insight of the problem.

**Comment by oliviertassinari** [comment]
@yoadsn Interesting approach! Have you tried implementing it? My only concern would be around performance. I'm not sure how it's gonna behave.
I see two other options:
- Removing react-motion for [animated](https://github.com/animatedjs/animated) as we do on the native platform but that's increasing the build size (288 kB vs 162kB without any compression).
- Prune the first render of react-motion in that case so we only keep the second one with a valid state.

**Comment by yoadsn** [comment]
@oliviertassinari I only crafted the example bin around your initial bin demonstrating the problem. I did not see react-swipeable-views' code back then and now I know you based that off a simpler version of this library. It proved this solves the problem.

It is clearly a hack, since you would like to manage the `translate` animation over the entire container but`TransitionMotion` wants to know your children to take into account their entering/leaving for animation window persistence.
Technically speaking, we could recreate the logic of `TransitionMotion` directly on top of `Motion` and in that case react-swipeable-views would have to keep around the dom elements of "removed" slides until their animation is done. I would think that is the best way to go.. Might go for a PR but I am not sure would have enough time to create the required tests to prove no regression bugs are intoduced.

pruning the first render seems even more error prone.. this heavily relies on the existing behavior of react-motion and the specific use case.

How does `animated` solve this problem? renders the immediate transition with the state change?

**Comment by vomchik** [comment]
I have the same problem

![image](https://d1ro8r1rbfn3jf.cloudfront.net/ms_70007/IOzejeos8VJecaEqrwdWGOX6jCpLNc/screencast%2B2016-12-23%2B10-21-46.gif?Expires=1482567745&Signature=FAGj4AAcz5WVNce2JXawUHwbpuB1XkObNgHrqL8NrZSyhIEjiACDDv8EcHmsn-JvODarLbb~sNn0bXChCUq81LVMQwtTWqvM3vgGKnn3h0KN5gLma65M~0HTJNvAlOCXusrJaQ3Q6v9BZZm34x1MwQBDz-14YJhLfN09-g-jWMfr3kO5kZN94Px8uBY94ElNqc43mmNpvFCt02L03LgjT~widSoCtz6adV1bwziGZ4baDZrjKAviyEQB5ses6YheLRG4sAGO65sNMei15MC2BVXwvT-2EmG-VUyhtCW0~vmWp3zwqnit~r2D1YkG-ciAqsRF4sqk4eB8UKulLNBPlA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

**Comment by vomchik** [comment]
Why it happen only in Safari? How can explain this?

**Comment by vomchik** [comment]
@oliviertassinari  did you know how fix this?

**Comment by oliviertassinari** [comment]
The solution is quite simple. I have removed the `react-motion` dependency, making the implementation lighter.

**Comment by yoadsn** [comment]
After reviewing the PR I would not call re-implementing DOM level css transitions "quite simple" but you seem to know what your doing here.. Thank you!
