### ISSUE TITLE
Option to modify swipe distance

### ISSUE THREAD

**Issue by JRGranell** [oliviertassinari/react-swipeable-views#229]
Hi @oliviertassinari thanks for the work you have done on this lib it's really good and I use it on most of the projects I'm involved with.

I'm on a project where we are using it to swipe through tiles on mobile and our design would like it to show the start of the next tile - to indicate that it can be pulled across. 

When swiping it naturally swipes 100% over to the next tile, I believe the code for that is here: 

https://github.com/oliviertassinari/react-swipeable-views/blob/e4c08f41636795fee760074c5b14cd16ea5c2ab8/packages/react-swipeable-views/src/SwipeableViews.js#L691

To preview some of the next tile, I can offset the tile by a percentage by setting slideStyle - that would bleed the next tile into view - but of course when swiped the area then gets hidden. 

I was thinking that if I could change the width that is translated then it wouldn't hide the bleeding edge? i.e. replace the * 100 on that line with a setting or parameter that could be passed through proptypes? I'd be interested in your thoughts or if you've come across this already.

Thanks,

JR

**Comment by oliviertassinari** [comment]
Thanks for the support. Have you seen the last demo of the documentation?
I think that it's what you are looking for:
![capture d ecran 2017-01-06 a 21 14 11](https://cloud.githubusercontent.com/assets/3165635/21731540/27815a68-d455-11e6-8a37-7995c82478d7.png)

**Comment by damusnet** [comment]
Hi @oliviertassinari 

Same here, I really like what you have done with this library and thank you very much for it.

I have the same issue/requirement, and I have been through Demo 12, but I think my use case is slightly different. Demo 12 allows you to peek at the next slide, but you can still only have one slide per screen-width. Here is what I am trying to accomplish:

![image](https://user-images.githubusercontent.com/433409/28476473-fddcb5e6-6e04-11e7-959e-b652aee46421.png)

There are two issues in this scenario. The first one, is that it scrolls one "screen-width" for each swipe. So in effect, page 2 looks like this:

![image](https://user-images.githubusercontent.com/433409/28476533-2fff0682-6e05-11e7-82fe-ba898fb8011c.png)

...when really I wished to have "slide n˚2" on the far left edge of the screen after the first swipe.

The second issue is that since slides are shorter than the screen-width, there are a number of empty pages that the user can scroll through at the end.

Do you see a way to accomplish that? If it's not already possible, would you be open to add that feature? I am happy to try and submit a pull request if you like the idea and with your guidance.

**Comment by damusnet** [comment]
Scratch that! I was able to achieve what I thought was `Issue n˚1`. Here is my code for anyone trying to do the same:

```jsx
<SwipeableViews
  style={{
    paddingLeft: spacing.normal,
    width: '40vw',
    overflow: 'visible',
  }}
  slideStyle={{
    paddingRight: spacing.normal,
    paddingBottom: spacing.normal,
    flex: 'none',
  }}
/>
```

The user can still scroll to what is essentially an empty page at the end, but that's less an issue I think.

What a great library!

**Comment by oliviertassinari** [comment]
:)

**Comment by kunal-arora** [comment]
@damusnet  Hey, is there any way to specify the number of slides ?

I implementing something like your recently viewed tabs, But the issue with that is the last slide will have empty space in the right,

**Comment by damusnet** [comment]
Not that I could find. We have the remaining space as well but decided it
was okay.
