### ISSUE TITLE
Handling null slide children? 

### ISSUE THREAD

**Issue by ofirpeer** [oliviertassinari/react-swipeable-views#271]
Is there a way to completely hide (Display: none) a slide container? In other words, i would like to give different slide containers different styles (SlideStyle applies the same style to all slide containers).

To get the same result, I tried to render some slides only if a certain condition was true (Even though I think it's not the greatest idea because the whole slide renders from scratch every time the condition is true ). 
For that I had something like this:

<SwipableViews>
    {slide1}
    {condition ? slide2 : null}
</SwipableViews>

but apparently null renders a blank slide. which is bad for me :-( 

Any thoughts?? 
Thanks :)

**Comment by ofirpeer** [comment]
Sorry i had a mistake in my question, I meant SlideStyle and not ContainerStyle.
I want to use different SlideStyles for different slides, aka applying different to the div that wraps the slide (<div aria-hidden="false" data-swipeable="true"... ).

If it's not possible, is there a value i can send as a slide that won't render? (this relates to the second part of the question)

**Comment by oliviertassinari** [comment]
Right, you can use `slideStyle` as well as `slideClassName` to do that task.

> but i still think that if a slide is null it shouldn't be rendered

That's a good question. What should be the expected result? I think that you are right here.

**Comment by maximux13** [comment]
@oliviertassinari I'm using this library too and I have a similar issue, I have a modal that have 3 tabs but I want to hide the last slide if the object doesn't have nothing to show in that tab, but instead I get an empty slide. I think that in that case nothing should be rendered instead.

**Comment by oliviertassinari** [comment]
I'm gonna label that issue `won't fix`. Support it would mean complexifing the source code, I would rather have users providing the right list of children on userland. Still what can warn against such wrong usage.

**Comment by ofirpeer** [comment]
Hey,
Sorry for late comment, but it might help @maximux13  .
When i was struggling with the problem i tried to play with the source code and this change in the render function solved my problem:
Sending null as a view will return null.
Didn't test it, so it might fail somewhere:

```
...
return (
      <div
        ref={(node) => { this.rootNode = node; }}
        style={Object.assign({}, axisProperties.root[axis], style)}
        {...other}
        {...touchEvents}
        onScroll={this.handleScroll}
      >
        <div
          ref={(node) => { this.containerNode = node; }}
          style={Object.assign({}, containerStyle, styles.container, containerStyleProp)}
          className="react-swipeable-view-container"
        >
          {Children.map(children, (child, indexChild) => {
           
          //CHANGE:
	   if(child == null){
	      return null;
	   }
	 //CHANGE END	
	
            if (isFirstRender && indexChild > 0) {
              return null;
            }

            let ref;
            let hidden = true;
            ...
```

Just wanted to share

**Comment by oliviertassinari** [comment]
@ofirpeer I wish the complexity was as simple on the library end but it's not. That's why I have introduced a warning as it's much simpler for users to take care of it.

**Comment by AntonioRedondo** [comment]
I came across with the same issue.

Basically if the child is `null`, `undefined` or not valid `react-swipeable-views` shouldn't render anything instead of rendering an empty `<div>` which becomes a blank swiping surface as it happens now.

This need is a common use case when the children you pass to `react-swipeable-views` are coming from iterating an array, and from some reason an array's position doesn't need to be rendered, then you return from that position `null`/`undefined`.

Wouldn't be a much time consuming task to make changes around [L817](https://github.com/oliviertassinari/react-swipeable-views/blob/c142cc80fc7bf92604b65e0ed47610803e2c05ad/packages/react-swipeable-views/src/SwipeableViews.js#L817) (plus updating tests) to return `null` when the child isn't valid?

If the changes are a more complex task then I think at least the ticket should be left opened. It looks like it's a feature with demand. It doesn't make much sense to render a blank swiping surface if a child is incorrect. With the warning in console is enough.

**Comment by sudhiryadav** [comment]
Any update on this as yet?

**Comment by M1chaelTran** [comment]
I do have to agree with @AntonioRedondo 
Please re-open this and allow PR to improve this library!

**Comment by Meyhem** [comment]
I have found workaround for the null empty views. Normally you pass Swipeable view children as react elements:
```
<SwipeableViews>
    <Component1 />
    <Component2 />
    {condition && <Component3 />
</SwipeableViews>
```
The third one causes empty view so workaround is to take SwipeableView children to array first and pass computed array as child to it. Like this:
```
const views = [
    <Component1 />,
    <Component2 />
]
if (condition) { 
    views.push(<Component3 />) 
}
...
<SwipeableViews>
    {views}
</SwipeableViews>
```
This does not cause third empty panel if condition is falsy, because its not passed as child (not null, not passed at all)
