### ISSUE TITLE
Component level knowledge of last slide.

### ISSUE THREAD

**Issue by LucasKA** [oliviertassinari/react-swipeable-views#287]
First off this component is incredible. It's one thats predictable and helpful. I couldn't figure this out on my own, so I'm asking here.

Because the slides are child based, its not necessarily mobile responsive. If you want more or less elements in a slide, you have to chunk the array, and thats fine.

Is there a way in the component to know if its on last child in the array, in a way that isn't state based?

The reason is, I added arrows to increment and decrement the slides for desktop, I hide the left arrow on the first slide, but the right arrow stays exposed, and just increments and adds an empty slide.

Thanks for any ideas.

**Comment by oliviertassinari** [comment]
> in a way that isn't state based?

What's wrong with a state-based solution? Controlling the `index` property sounds like the best solution. You could also keep both arrow, I haven't added any [here](https://www.doctolib.fr/for-doctors/save-time).

**Comment by LucasKA** [comment]
@oliviertassinari I guess there's nothing wrong with a state based solution, as much as responsively knowing which one is the last index.

https://gist.github.com/LucasKA/4a6558a00c7ca70f38c502d72d936963

**Comment by oliviertassinari** [comment]
Oh I see. I think that you should be using the `count` value at your advantage. You could have a instance variable containing it. The core of the issue seems to be with your responsive solution. 
```jsx
renderSwipeableViews = count => (
```
If you are interested in different solution, we have been developing a [withWidth](https://github.com/callemall/material-ui/blob/next/src/utils/withWidth.js) Higher-order Component on Material-UI.
