### ISSUE TITLE
 You are setting animateHeight to true but you are also providing a custom height. The custom height has a higher priority than the animateHeight property. So animateHeight is most likely having no effect at all.

### ISSUE THREAD

**Issue by dsslimshaddy** [oliviertassinari/react-swipeable-views#319]
This warning is showing when i have a custom `minHeight` not `height`.

Although `animateHeight` is working fine
 
```
<SwipeableViews containerStyle={{minHeight: swipeableHeight}} animateHeight
>
...
```

**Comment by yohio** [comment]
Having the same warning as well

**Comment by geooogle** [comment]
is it possible to remove this warning?

**Comment by oliviertassinari** [comment]
What about [using this pattern instead](https://github.com/oliviertassinari/react-swipeable-views/blob/master/docs/src/demo/DemoAnimateHeight.js#L10) in order to avoid the warning?

**Comment by yohio** [comment]
The issue is mostly because the situation is as follows:
I have a reactive view that updates when something is changed, it's a list of items similar to a ToDo list.
Once I finish a task it updates the list cards and since the animate height is useful to me because each ToDo item has the 2nd swipe for details that has more content than the Title on the 1st.
I need the min height to prevent the view from pushing users to the top when the entire list turns to 0 height and grows to the size of the card which also is very annoying flashing the view.

I would say that this warning should be more of a "console.info" and I would think it is useful if one is to set a fixed height or max-height, min-height is not going to block the swipeable views from growing but it is going to set a base to which size it will grow from.
While I agree that it could be misused and render the animated height useless, it is useful to others who need it not to have the warning as it might present a problem when deploying and having the app under review on the app/play stores.

Is it possible to change the warning to be an info and to remove the min-height from the logic for it?

Thanks

**Comment by dsslimshaddy** [comment]
@oliviertassinari  that pattern also works

**Comment by yohio** [comment]
Didn't work for me, everything still sizes up from a height of 0
