### ISSUE TITLE
Programmatically trigger updateHeight()

### ISSUE THREAD

**Issue by stfny222** [oliviertassinari/react-swipeable-views#339]
I'm using  react-swipeable-views to animate the Material-UI tabs transition, and I must say I found this library very useful.

However, I enabled the animateHeight property since the height of my slides are very different from each other. It works great when swiping between them or changing tabs, but if the content of the current slide changes, the container doesn't resize.

Is it possible to not only fire the updateHeight() method when the current slide changes, but also when its content change?

**Comment by ashl1** [comment]
Hmmm... Looks like the same source of the question as I mention in #159 
Currently we has one more problem with nested swipeable-views which I will describe in next issue

**Comment by ashl1** [comment]
Did you try to use `ref` and `ref.updateHieght()`?

**Comment by oliviertassinari** [comment]
> Did you try to use ref and ref.updateHieght()?

@ashl1 Does that work? Maybe we could be exposing a callback property close to the ref pattern to make it work.

**Comment by ashl1** [comment]
This's really strange because I cannot reproduce the problem on simple model. Will go deeper.

**Comment by ashl1** [comment]
Hmmm... If the slide isn't changed the height changes relative to its context.
Also, I've been found `this.context.swipeableViews.slideUpdateHeight()` method which might help to force update the height, am I right?
Anyway I can't see the problem when use `autoHeight` prop and dynamically changed content if content don't contain animated transition itself.

@stfny222 Could you provide an example of the problem?
@oliviertassinari The real problem I mentioned #344 happens if the slide content changes with animation (so the `activeSlide.offsetHeight` changes every frame). The only solution I can see is set new height manually from outside the SwipeableView.
Can I make a PR for the changes? Could you @oliviertassinari look at it?

**Comment by stfny222** [comment]
@ashl1 here's my problem. I have a list of comments, when more comments are loaded, the slide won't resize. Here's an example:

![animateheight](https://user-images.githubusercontent.com/9699705/30515609-168e5bbc-9af1-11e7-80da-09d0f173e322.gif)

And this is how my react DOM tree looks like:

![selection_191](https://user-images.githubusercontent.com/9699705/30515632-8dcbe46a-9af1-11e7-92a0-477003321f35.png)

I'm gessing this happens since the content that changes is not a direct child from ReactSwipableView, but it's deeper in the tree because of the multiple apollo-client HOCs.

I came to this conclusion since I tried with a much simpler example and it worked fine:

![simpleexample](https://user-images.githubusercontent.com/9699705/30515667-0db63b62-9af2-11e7-9f78-bc6e2829bc8b.gif)

This is how the tree looks like here:

![selection_192](https://user-images.githubusercontent.com/9699705/30515661-f8da1ed4-9af1-11e7-96cc-e5a0b78404e6.png)

> Maybe we could be exposing a callback property close to the ref pattern to make it work



I think the solution proposed by @oliviertassinari should work great
