### ISSUE TITLE
Add option for "dead space"

### ISSUE THREAD

**Issue by wallzero** [oliviertassinari/react-swipeable-views#350]
I am using both `react-swipeable-views` and [`react-sidebar`](https://github.com/balloob/react-sidebar) in a project. There is an issue where swiping open the sidebar also swipes the views. I am not sure what the best solution would be in this case, but I was thinking it would be nice with there was an option for left, right, top, and bottom "dead space" in `react-swipeable-views`. This way `react-sidebar`'s touch would occupy the disabled space the two wouldn't interfere.

I am open for suggestions if there is a better way of going about this. Thanks!

**Comment by oliviertassinari** [comment]
The best option would probably to add a div prevent the SwipeableView to receive the touch events.

**Comment by mindnektar** [comment]
Could you provide an example on how to do this? Having a div like this within the SwipeableView does not work, swiping within it still triggers SwipeableView:

```
<div
    onTouchStart={(event) => { event.stopPropagation(); event.preventDefault(); }}
    onTouchMove={(event) => { event.stopPropagation(); event.preventDefault(); }}
>
    [...]
</div>
```

**Comment by oliviertassinari** [comment]
> Having a div like this within the SwipeableView 

@mindnektar Have you tried putting the div **outside** of the component? However, calling  stopPropagation inside should definitely prevent the swipe. For instance: https://github.com/oliviertassinari/react-swipeable-views/issues/347#issuecomment-346952941

**Comment by mindnektar** [comment]
Thanks for your answer! My specific use-case is a slider within a swipeable view. I want to be able to  drag the slider handle using my finger without triggering any SwipeableViews handlers, so I tried wrapping my slider in a div that stops all touch event propagations. For some reason, this does not work, however. Because said slider is supposed to be part of the swipeable view, I cannot put it outside of it. The issue you pointed to seems to be dealing with mouse events, which I'm not handling at all.

Another thing: I noticed that the slider component itself is stopping touch event propagation. When I drag the slider handle, no touch events are propagated to my surrounding div--yet the SwipeableView is still doing its thing. Why would that be?

**Comment by oliviertassinari** [comment]
@mindnektar Could you setup a simple reproduction example on codesandbox? I think I know what's wrong.

**Comment by mindnektar** [comment]
Gladly. Here's a very reduced example: https://codesandbox.io/s/8xp3pj6k7l

**Comment by thientran1707** [comment]
@mindnektar do not use onTouchStart, onTouchMove and onTouchEnd, if you use addEventListener() then it will work

**Comment by mindnektar** [comment]
I understand, but I cannot do that because the slider component that is using these events is an external dependency.

**Comment by henryhs97** [comment]
Was someoen able to figure this out? I'm trying to also make some 'dead space' within a SwipeableViews component because I'm adding a MaterialUI slider (and dragging the slider causes the whole view to be swiped instead).

**Comment by tuoxiansp** [comment]
Met the same problem: react-swipeable-views + react-slider.

Because the two libs all need to ensure keep on swiping/sliding while user's finger/mouse left target element, so they all used `document.addEventListener('touchmove', handler)` rather than `onTouchMove`.

Attemping to stop bubbling between swipeable view and slider will block both of them.

My resolution was forking react-slider and modify the add event method with `useCapture: true`:

```javascript
addEventListener('touchmove', handler, true) //use capture
```

This will ensure the slider could receive touch events.

Then create a 'DeadSpace' component to stop bubbling events to swiper.

```tsx
const DeadSpace: FC = ({ children }) => {
  const ref = useRef<HTMLDivElement>(null);
  useLayoutEffect(() => {
    const stopBubble = (e) => e.stopPropagation();
    ref.current?.addEventListener("touchmove", stopBubble);

    return () => {
      ref.current?.removeEventListener("touchmove", stopBubble);
    };
  }, []);

  return <div ref={ref}>{children}</div>;
};
```

And use it to wrap slider like this:

```jsx
<SwipeableView>
  <DeadSpace>
    <Slider />
  </DeadSpace>
</SwipeableView>
```
