### ISSUE TITLE
mobile safari swipe from the edge of the screen

### ISSUE THREAD

**Issue by zsolt-dev** [oliviertassinari/react-swipeable-views#531]
- [x] I have searched the [issues](https://github.com/oliviertassinari/react-swipeable-views/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
It would be nice if react-swipeable-views would disable the default sarafi mobile swipe back gesture.

## Current Behavior
1. when I swipe from the edge of the screen, it does the default safari swipe back gesture
2. when I swipe anywhere else, it works as expected

## Your Environment

I am using it indirectly via react-swipeable-routes

| Tech                   | Version |
|------------------------|---------|
| react-swipeable-views  |  0.12.18       |
| React                  |    16.8.6     |
| platform               |    latest safari on iphone     |

**Comment by oliviertassinari** [comment]
iOS swipe back / forward can't be disabled. However, the component could ignore the events on the edges

**Comment by fabianjj** [comment]
@oliviertassinari, do you know a good way to intercept touch events for these areas of the screen so that the SwipeableViews can ignore them? I've tried wrapping the component in a div and use preventDefault() and stopPropagation() for those locations, but none of them seem to go though on either chrome or safari.

**Comment by suiyuan2009** [comment]
@fabianjj , you can try to implement a `onTouchStart` function to handle edge case.
